### ISSUE TITLE
Desktop environment has become very laggy

### ISSUE THREAD

**Issue by Atukii** [smmr0/gnome-reorder-workspaces#17] opened 2023-01-19 09:51 UTC
Installed the extension via https://extensions.gnome.org/extension/3685/reorder-workspaces/, once installed the desktop environment has become laggy. Most noticeable when using a browser trying to switch tabs or navigating around a file explorer. Before the installation my desktop environment didn't have this issue. 

Removing the extension hasn't actually fixed the problem, I've noticed that other users have reported the same problem. Any suggestions as to where the extension is located, perhaps i could scrub it manually and see if it fixes the lag.

**Comment by smmr0** [comment] 2023-01-30 06:06
Please see #6; there will be a new extension setting that should fix the choppy animation when opening/closing the overview.

However that shouldn't cause any lag with the actions you listed (switching browser tabs and navigating a file explorer), and no effects at all should persist after removing the extension. I'd guess that something else must be causing that.

> Any suggestions as to where the extension is located[…]

When installed, the extension should be stored under `~/.local/share/gnome-shell/extensions/`.

I'm going to close this issue for now, but if it isn't resolved by the new setting in the next release and you can confirm that it's caused by this extension, let me know and I'll reopen it.

**Closed as not planned by smmr0** 2023-01-30 06:06 UTC
