### ISSUE TITLE
Using Left and Right arrow

### ISSUE THREAD

**Issue by kwastek** [smmr0/gnome-reorder-workspaces#14] opened 2022-08-04 08:51 UTC
I love your extension. It's extremely useful. Unfortunately, they arrow keys assigned for moving the workspaces are very unintuitive: arrow up moves to the left, arrow down move to the right. Could you make it use left and right arrows? You could leave the up and down arrows as they are for the people who got used to using them, but add left and right arrow as well.

**Comment by smmr0** [comment] 2022-08-06 03:03
Possible duplicate of #10; should hopefully have been resolved via #11 (released in [v11](https://github.com/smmr0/gnome-reorder-workspaces/releases/tag/v11)+).

Can you please ensure that you're updated to v11 or greater and then check whether keyboard shortcut preferences are available via `gnome-extensions-app`?

**Closed as completed** 2022-08-22 03:19 UTC
Labels: duplicate
